src/Entity/Tag.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TagRepository")
 * @ORM\Table(name="app_tag")
 */
class Tag
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Device", mappedBy="tags")
     */
    private $Devices;

    /**
     * @ORM\Column(type="integer", nullable=true, name="sort")
     */
    private $sort;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Call", mappedBy="tag")
     */
    private $calls;

    /**
     * @ORM\Column(type="boolean")
     */
    private $cluster;

    public function __construct()
    {
        $this->Devices = new ArrayCollection();
        $this->calls = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Device[]
     */
    public function getDevices(): Collection
    {
        return $this->Devices;
    }

    public function addDevice(Device $device): self
    {
        if (!$this->Devices->contains($device)) {
            $this->Devices[] = $device;
        }

        return $this;
    }

    public function removeDevice(Device $device): self
    {
        if ($this->Devices->contains($device)) {
            $this->Devices->removeElement($device);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->name;
    }

    /**
     * @return mixed
     */
    public function getSort()
    {
        return $this->sort;
    }

    /**
     * @param mixed $sort
     */
    public function setSort($sort): void
    {
        $this->sort = $sort;
    }

    /**
     * @return Collection|Call[]
     */
    public function getCalls(): Collection
    {
        return $this->calls;
    }

    public function addCall(Call $call): self
    {
        if (!$this->calls->contains($call)) {
            $this->calls[] = $call;
            $call->setTag($this);
        }

        return $this;
    }

    public function removeCall(Call $call): self
    {
        if ($this->calls->contains($call)) {
            $this->calls->removeElement($call);
            // set the owning side to null (unless already changed)
            if ($call->getTag() === $this) {
                $call->setTag(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function isCluster()
    {
        return $this->cluster;
    }

    /**
     * @param mixed $cluster
     */
    public function setCluster($cluster): void
    {
        $this->cluster = $cluster;
    }

    public function getDeviceIdString() {

        $deviceIds = [];

        /** @var Device $device */
        foreach ($this->getDevices() as $device) {
            $deviceIds[] = $device->getId();
        }

        return implode(',', $deviceIds);
    }
}

src/Form/DashboardType.php
<?php

namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DashboardType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('devices', CollectionType::class, [
                'label' => false,
                'entry_type' => DeviceType::class,
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false,
                'entry_options' => [
                    'attr' => ['class' => 'device--'],
                ],
            ])
            ->add('save', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use App\Entity\Call;
use App\Entity\Device;
use App\Entity\Scene;
use App\Entity\Tag;
use App\Form\CallsType;
use App\Form\DevicesType;
use App\Form\ScenesType;
use App\Form\TagsType;
use App\Services\DashboardService;
use App\Services\YeelightService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class DashboardController extends AbstractController
{
    /** @var YeelightService $yeelightService */
    private $yeelightService;

    /** @var DashboardService $dashboardService */
    private $dashboardService;

    /**
     * DashboardController constructor.
     */
    public function __construct(YeelightService $yeelightService, DashboardService $dashboardService)
    {
        $this->yeelightService = $yeelightService;
        $this->dashboardService = $dashboardService;
    }

    public function index(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        $devices = $em->getRepository(Device::class)->findOrdered();
        $tags =  $em->getRepository(Tag::class)->findOrdered(); //todo: no clusters
        $scenes =  $em->getRepository(Scene::class)->findAll();

        $sceneLabels = $em->createQuery('SELECT s.label FROM App\Entity\Scene s GROUP BY s.label')->getResult();
        $sceneLabels = array_column($sceneLabels, 'label');
        $sceneLabels = array_filter($sceneLabels);

        $fixtures = $this->dashboardService->getAllFixtures();

        return $this->render('dashboard/dashboard.html.twig', [
            'sceneLabels' => $sceneLabels,
            'scenes' => $scenes,
            'fixtures' => $fixtures,
            'tags' => $tags,
        ]);
    }

    public function devices(Request $request) {
        if($request->get('action') === 'scan_yeelights') {
            $this->yeelightService->scanForYeelights();
            return $this->redirectToRoute('app.devices', []);
        }

        $em = $this->getDoctrine()->getManager();

        $devices = $em->getRepository(Device::class)->findOrdered();
        $form = $this->createForm(DevicesType::class, ['devices' => $devices]);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $formData = $form->getData();
            $formDevices = $formData['devices'];

            //persist all new tags
            foreach ($formDevices as $formDevice) {
                $em->persist($formDevice);
            }

            //update $devices
            $devices = $em->getRepository(Device::class)->findOrdered();

            //remove tags that aren't pushed anymore
            foreach ($devices as $device) {
                if(!in_array($device, $formDevices, true)) {
                    $em->remove($device);
                }
            }

            $em->flush();
        }

        return $this->render('dashboard/devices.html.twig', [
            'form' => $form->createView(),
            'devices' => [],
        ]);
    }

    public function tags(Request $request) {
        $em = $this->getDoctrine()->getManager();

        $tags = $em->getRepository(Tag::class)->findAll();
        $form = $this->createForm(TagsType::class, ['tags' => $tags]);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $formData = $form->getData();
            $newTags = $formData['tags'];

            //persist all new tags
            foreach ($newTags as $tag) {
                $em->persist($tag);
            }

            //update $tags
            $tags = $em->getRepository(Tag::class)->findAll();

            //remove tags that aren't pushed anymore
            foreach ($tags as $tag) {
                if(!in_array($tag, $newTags)) {
                    $em->remove($tag);
                }
            }

            $em->flush();
        }

        return $this->render('dashboard/tags.html.twig', [
            'form' => $form->createView(),
            'tags' => [],
        ]);
    }

    public function scenes(Request $request) {
        $em = $this->getDoctrine()->getManager();
        $scenes = $em->getRepository(Scene::class)->findAll();

        $form = $this->createForm(ScenesType::class, ['scenes' => $scenes]);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $formData = $form->getData();
            $formScenes = $formData['scenes'];

            //persist all new scenes
            foreach ($formScenes as $scene) {
                $em->persist($scene);
            }

            //update $scenes
            $scenes = $em->getRepository(Scene::class)->findAll();

            //remove $scenes that aren't pushed anymore
            foreach ($scenes as $scene) {
                if(!in_array($scene, $formScenes)) {
                    $em->remove($scene);
                }
            }
            $em->flush();
        }

        $sceneLabels = $em->createQuery('SELECT s.label FROM App\Entity\Scene s GROUP BY s.label')->getResult();
        $sceneLabels = array_column($sceneLabels, 'label');
        $sceneLabels = array_filter($sceneLabels);

        return $this->render('dashboard/scenes.html.twig', [
            'sceneLabels' => $sceneLabels,
            'ip' => $this->getHost(),
            'form' => $form->createView(),
        ]);
    }

    public function calls(Request $request, $scene) {
        $em = $this->getDoctrine()->getManager();
        /** @var Scene $scene */
        $scene = $em->getRepository(Scene::class)->find($scene);
        $sceneCalls = $scene->getCalls();

        $form = $this->createForm(CallsType::class, ['calls' => $scene->getCalls()]);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $formCalls = [];
            foreach ($form->get('calls') as $callData)
            {
                $deviceTag = $callData->get('deviceTag')->getData();
                $api = $callData->get('api')->getData();                //ignored for now since can only be Yeelight

                /** @var Call $call */
                $call = $callData->getData();

                if($deviceTag[0] === 't') {
                    /** @var Tag $tag */
                    if(null === $tag = $em->getRepository(Tag::class)->find(substr($deviceTag, 1))) {
                        throw new NotFoundHttpException('Unknown tag for id '.substr($deviceTag, 1));
                    }

                    $call->setDevice(null);
                    $call->setTag($tag);
                }
                else {
                    /** @var Device $device */
                    if(null === $device = $em->getRepository(Device::class)->find($deviceTag)) {
                        throw new NotFoundHttpException('Unknown tag for id '.$deviceTag);
                    }

                    $call->setDevice($device);
                    $call->setTag(null);
                }


                $formCalls[] = $call;

                $call->setScene($scene);
                $em->persist($call);
            }

            //remove $sceneCalls that aren't pushed anymore
            foreach ($sceneCalls as $call) {
                if(!in_array($call, $formCalls)) {
                    $em->remove($call);
                }
            }
            $em->flush();
        }

        return $this->render('dashboard/calls.html.twig', [
            'scene' => $scene,
            'form' => $form->createView(),
        ]);
    }

    public function api(Request $request) {
        $em = $this->getDoctrine()->getManager();

        $tags = $em->getRepository(Tag::class)->findAll();
        $devices = $em->getRepository(Device::class)->findOrdered();

        return $this->render('dashboard/api.html.twig', [
            'ip' => $this->getHost(),
            'tags' => $tags,
            'devices' => $devices,
            'scenes' => [],
        ]);
    }

    public function screen(Request $request) {
        $em = $this->getDoctrine()->getManager();

        return $this->render('dashboard/screen.html.twig', [
            'devices' => [],
            'scenes' => [],
        ]);
    }

    private function getHost() {
        $ip = $_SERVER['REMOTE_ADDR'];
        if($_SERVER['SERVER_PORT'] !== 80 && $_SERVER['SERVER_PORT'] !== 443) {
            $ip .= ':'. $_SERVER['SERVER_PORT'];
        }

        return $ip;
    }
}

templates/dashboard/_menu.html.twig
<div class="nav flex-column nav-pills">
    <a class="nav-link{% if pageTitle == 'Dashboard' %} active{% endif %}" href="{{ path('app.dashboard') }}">Dashboard</a>
    <a class="nav-link{% if pageTitle == 'Devices' %} active{% endif %}" href="{{ path('app.devices') }}">Devices</a>
    <a class="nav-link{% if pageTitle == 'Tags' %} active{% endif %}" href="{{ path('app.tags') }}">Tags</a>
    <a class="nav-link{% if pageTitle == 'Scenes' %} active{% endif %}" href="{{ path('app.scenes') }}">Scenes</a>
    <a class="nav-link{% if pageTitle == 'API' %} active{% endif %}" href="{{ path('app.api') }}">API</a>
    <a class="nav-link{% if pageTitle == 'Screen' %} active{% endif %}" href="{{ path('app.screen') }}">Screen</a>
</div>

templates/dashboard/calls.html.twig
{% extends 'dashboard/index.html.twig' %}

{% set pageTitle = 'Calls ('~scene.name~')' %}
{#{% set pageTitle = 'Calls ('~'/'~')' %}#}


{% block stylesheets %}
    <link rel="stylesheet" href="/css/bootstrap/bootstrap-select.min.css" />
{% endblock %}

{% block content %}
    {{ form_start(form) }}

    <div class="js-calls"
           data-prototype="{% apply escape %}{% include 'dashboard/_partials/call.html.twig' with {call: form.calls.vars.prototype } only %}{% endapply %}"
    >
    {% for call in form.calls %}
        {% include 'dashboard/_partials/call.html.twig' with {call: call } only %}
    {% endfor %}
    </div>

    <button type="button"
            class="btn btn-outline-success mt-3 js-add-widget"
            data-list-selector=".js-calls">add call</button>

    <div class="mt-5">
        {{ form_widget(form.save) }}
    </div>

    {{ form_end(form) }}
{% endblock %}

{% block javascripts %}
    <script src="/js/popper/popper.min.js"></script>
    <script src="/js/bootstrap/bootstrap.bundle.min.js"></script>
    <script src="/js/bootstrap/bootstrap-select.min.js"></script>
    <script src="/js/axios/axios.min.js"></script>
    <script>
        // add-collection-widget.js
        $(document).ready(function () {
            $('.js-add-widget').click(function (e) {
                var list = $($(this).attr('data-list-selector'));
                var counter = list.data('widget-counter') || list.children().length;

                var newWidget = list.attr('data-prototype');
                newWidget = newWidget.replace(/__callid__/g, counter);
                counter++;
                list.data('widget-counter', counter);

                $(list).append(newWidget);
                $('.selectpicker').selectpicker('refresh');
                newWidget = $('.js-call').last()[0];
                console.log('newWidget', newWidget);
                updatePrefix(newWidget);

                bindEventsOnDropdownChange([newWidget.querySelector('.js-tag-device')]);
                bindEventsOnDropdownChange([newWidget.querySelector('.js-api')]);
            });
        });

        //remove logic
        $(document.body).on('click', '.js-remove-call', function (e) {
            e.preventDefault();

            var callCount = $(this.closest('.js-calls')).find('tr').length;
            $(this).closest('.js-call').remove();
        });

        document.querySelectorAll('.js-tag').forEach(function (el) {
            el.addEventListener('change', function(e) {
                $(e.currentTarget).closest('.js-device').value = '';
            });
        });

        //update api prefix
        bindEventsOnDropdownChange(document.querySelectorAll('.js-tag-device, .js-api'));

        function updatePrefix($callEl) {
            $callEl.querySelector('.js-url-prefix').textContent = '/api/' + $callEl.querySelector('select.js-api').value + '/' + $callEl.querySelector('select.js-tag-device').value + '/';
        }

        function bindEventsOnDropdownChange(elms) {
            elms.forEach(function (el) {
                el.addEventListener('change', function(e) {
                    updatePrefix($(e.currentTarget).closest('.js-call')[0]);
                });

                updatePrefix($(el).closest('.js-call')[0]);
            });
        }

        //execute ajax call
        document.querySelectorAll('.js-ajax').forEach(function (el) {
            el.addEventListener('click', function (e) {
                e.preventDefault();
                const call = $(e.currentTarget).closest('.js-call');
                const url = call.find('.js-url-prefix').text() + call.find('.js-url').val();
                axios.get(url)
                    .then(function (response) {
                        console.log(response);
                    })
                    .catch(function (error) {
                        console.log(error);
                    })
                ;
            });
        });
    </script>
{% endblock %}

templates/dashboard/dashboard.html.twig
{% extends 'dashboard/index.html.twig' %}

{% set pageTitle = 'Dashboard' %}

{% block stylesheets %}
    <link rel="stylesheet" href="/css/slider.css"/>
{% endblock %}

{% block content %}
<div>
    <h2 class="mt-3">Scenes</h2>
    {% for sceneLabel in sceneLabels %}
        <div class="ml-2 mt-3">
            <h5 class="text-secondary">{{ sceneLabel }}</h5>
            {% for scene in scenes %}
                {% if scene.label == sceneLabel %}
                    <button type="button" class="btn btn-outline-primary btn-lg js-ajax" data-url="{{ path('api.scene.trigger', {'slug': scene.slug}) }}">{{ scene.name }}</button>
                {% endif %}
            {% endfor %}
        </div>
    {% else %}
        <p>There are no scenes configured</p>
        <a href="{{ path('app.scenes') }}" class="btn btn-success">create scene</a>
    {% endfor %}
    <h2 class="mt-5">Tags</h2>
    {% for tag in tags %}
        <div class="row d-flex align-items-center js-tag" data-devices="{{ tag.deviceIdString }}">
            <div class="col-md-5">
                <span class="btn btn-primary">{{ tag.name }}<span class="badge badge-light ml-2">{{ tag.devices|length }}</span></span>
            </div>
            <div class="col-md-7 py-2 align-items-center d-flex">
                <div class="btn-group mr-3" role="group" aria-label="Button group with nested dropdown">
                    <button type="button" class="btn btn-outline-primary js-ajax" data-url="{{ path('api.yeelight.execute', {'target': 't'~tag.id, 'method': 'set_power', 'params': 'on,sudden,0'}) }}">On</button>
                    <button type="button" class="btn btn-outline-primary js-ajax js-disable-when-off" data-url="{{ path('api.yeelight.execute', {'target': 't'~tag.id, 'method': 'set_power', 'params': 'off,sudden,0'}) }}">Off</button>
                    <button type="button" class="btn btn-outline-primary js-ajax js-disable-when-off" data-url="{{ path('api.yeelight.execute', {'target': 't'~tag.id, 'method': 'set_ct_abx', 'params': '3030,sudden,0'}) }}">WW</button>
                </div>
                <span class="flex-grow-1">
                    <input type="range" min="1" max="100" class="slider js-slider-group js-disable-when-off" id="slider-device-t{{ tag.id }}" data-url="{{ path('api.yeelight.execute', {'target': 't'~tag.id, 'method': 'set_bright', 'params': '__brightness__,sudden,50'}) }}">
                </span>
            </div>
        </div>

    {% endfor %}
    <h2 class="mt-5">Devices</h2>


    {% for key, fixture in fixtures %}
        <div class="row js-yeelight py-3" data-id="{{ key }}">
            <div class="col-2 col-md-1 align-self-center d-flex align-items-baseline">
                <img src="{{ 'img/icons/'~fixture.type|replace({' ': ''})~'.png' }}" width="48" height="48" alt="icon yeelight">
                {% if fixture.isCluster %}
                    <i class="fas fa-layer-group ml-1"></i>
                {% endif %}
            </div>
            <div class="col-5 col-md-2 align-self-center">
                {{ fixture.name }}
            </div>
            <div class="col-5 col-md-2 align-self-center">
                <span><i class="fas fa-lightbulb fa-lg js-icon-lamp"></i></span>
                <span class="js-brightness"></span>
            </div>
            <div class="col-md-7 py-2 align-items-center d-flex">
                <div class="btn-group mr-3" role="group" aria-label="Button group with nested dropdown">
                    {% if has_device_option(fixture.type, constant('App\\Services\\DeviceOptionsService::ACTION_ON_OFF')) %}
                        <button type="button" class="btn btn-outline-primary js-ajax" data-url="{{ path('api.yeelight.execute', {'target': key, 'method': 'set_power', 'params': 'on,sudden,0'}) }}">On</button>
                        <button type="button" class="btn btn-outline-primary js-ajax js-disable-when-off" data-url="{{ path('api.yeelight.execute', {'target': key, 'method': 'set_power', 'params': 'off,sudden,0'}) }}">Off</button>
                    {% endif %}
                    {% if has_device_option(fixture.type, constant('App\\Services\\DeviceOptionsService::ACTION_WW')) %}
                        <button type="button" class="btn btn-outline-primary js-ajax js-disable-when-off" data-url="{{ path('api.yeelight.execute', {'target': key, 'method': 'set_ct_abx', 'params': '3030,sudden,0'}) }}">WW</button>
                    {% endif %}
                    {% if has_device_option(fixture.type, constant('App\\Services\\DeviceOptionsService::ACTION_OPEN_IN_BROWSER')) %}
                        <a href="http://{{ fixture.ip }}" target="_blank" class="btn btn-outline-primary"><span class="fa fa-chrome text-primary"></span></a>
                    {% endif %}
                </div>
                {% if has_device_option(fixture.type, constant('App\\Services\\DeviceOptionsService::ACTION_SLIDER_BRIGHTNESS')) %}
                    <span class="flex-grow-1">
                        <input type="range" min="1" max="100" class="slider js-slider js-disable-when-off" id="slider-device-{{ key }}" data-url="{{ path('api.yeelight.execute', {'target': key, 'method': 'set_bright', 'params': '__brightness__,sudden,50'}) }}">
                    </span>
                {% endif %}
            </div>
            <div class="col-0 col-md-1"></div>
            <div class="col-12 col-md-11 d-flex align-items-center">
                <span class="fas fa-tag dark-gray"></span>
                {% for tag in fixture.tags %}
                    <span class="ml-2 badge badge-pill badge-primary">{{ tag }}</span>
                {% endfor %}
            </div>
        </div>
    {% else %}
        <p>There are no registered devices</p>
        <a href="{{ path('app.devices') }}" class="btn btn-success">register device</a>
    {% endfor %}
    </div>
{% endblock %}

{% block javascripts %}
    <script src="/js/bootstrap/bootstrap.js"></script>
    <script src="/js/axios/axios.min.js"></script>
    <script src="/js/helpers.js"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function(event) {
            document.querySelectorAll('.js-device-info-action').forEach(function (el) {
                el.addEventListener('click', function (e) {
                    const $infoBlock = document.querySelector('.js-device-info-' + e.currentTarget.dataset.row);
                    $infoBlock.classList.toggle('d-none');
                    el.classList.remove('btn-outline-primary', 'btn-primary');
                    el.classList.add($infoBlock.classList.contains('d-none') ? 'btn-outline-primary' : 'btn-primary');
                });
            });

            document.querySelectorAll('.js-ajax').forEach(function (el) {
                el.addEventListener('click', function (e) {
                    updateLight(e.currentTarget.dataset.url, [$(el).closest('.js-yeelight').data('id')]);
                });
            });
        });

        function updateLightIcons(lightId = 0) {
            lightId = Number(lightId);
            document.querySelectorAll('.js-yeelight').forEach(function (el) {
                if(lightId === 0 || lightId === Number(el.dataset.id)) {
                    axios.get('/api/yeelight/' +  el.dataset.id + '/get_prop/power,bright,color_mode,ct,rgb')
                        .then(function (response) {
                            const data = response.data.result;

                            if(data[0] === 'on') {
                                if(data[2] === '1') {
                                    el.querySelector('.js-icon-lamp').setAttribute('style', 'color: #'+rgbToHex(Number(data[4])));
                                }
                                else if(data[2] === '2') {
                                    el.querySelector('.js-icon-lamp').setAttribute('style', 'color: #'+colorTemperatureToHex(Number(data[3])));
                                }

                                el.querySelectorAll('.js-disable-when-off').forEach(function (actionBtn) {
                                    actionBtn.disabled = true;
                                });
                            }
                            else {
                                el.querySelector('.js-icon-lamp').setAttribute('style', 'color: #000000');

                            }

                            el.querySelector('.js-brightness').textContent = data[1] + '%';
                            el.querySelector('.js-slider').value = data[1];

                            // enable/disable action buttons when on/of
                            el.querySelectorAll('.js-disable-when-off').forEach(function (actionBtn) {
                                actionBtn.disabled = data[0] !== 'on';
                            });
                        })
                        .catch(function (error) {
                            // handle error
                        });
                }
            })
        }

        //slider logic
        document.querySelectorAll('.js-slider').forEach(function (el) {
            el.addEventListener('mouseup', function (e) {
                updateLight(e.currentTarget.dataset.url.replace('__brightness__', e.currentTarget.value), [$(e.currentTarget).closest('.js-yeelight').data('id')]);
            });

            el.addEventListener('touchend', function (e) {
                updateLight(e.currentTarget.dataset.url.replace('__brightness__', e.currentTarget.value), [$(e.currentTarget).closest('.js-yeelight').data('id')]);
            });
        });

        document.querySelectorAll('.js-slider-group').forEach(function (el) {
            el.addEventListener('mouseup', function (e) {
                updateLight(e.currentTarget.dataset.url.replace('__brightness__', e.currentTarget.value), $(e.currentTarget).closest('.js-tag').data('devices').split(','));
            });

            el.addEventListener('touchend', function (e) {
                updateLight(e.currentTarget.dataset.url.replace('__brightness__', e.currentTarget.value), $(e.currentTarget).closest('.js-tag').data('devices').split(','));
            });
        });

        updateLightIcons();

        function updateLight(url, lightIds) {
            axios.get(url)
                .then(function (response) {
                    // handle success
                    lightIds.forEach(lightId => updateLightIcons(lightId));
                })
                .catch(function (error) {
                    // handle error
                    console.log(error);
                })
            ;
        }
    </script>
{% endblock %}

templates/dashboard/devices.html.twig
{% extends 'dashboard/index.html.twig' %}

{% set pageTitle = 'Devices' %}

{% block stylesheets %}
    <link rel="stylesheet" href="/css/bootstrap/bootstrap-select.min.css" />
{% endblock %}

{% block content %}

    {{ form_start(form) }}

    <table>
        <thead></thead>
        <tbody class="js-tbody-devices"
               data-prototype="{% apply escape %}{% include 'dashboard/_partials/device.html.twig' with {device: form.devices.vars.prototype } only %}{% endapply %}">
        {% for device in form.devices %}
            {% include 'dashboard/_partials/device.html.twig' with {device: device} only %}
        {% endfor %}
        </tbody>
    </table>

    <div>
        <button type="button" class="btn btn-outline-success mt-3 js-add-widget" data-list-selector=".js-tbody-devices">add device</button>
    </div>

    <div class="mt-5">
        {{ form_widget(form.save) }}
        <a href="{{ path('app.devices', {'action':'scan_yeelights'}) }}" type="button" class="btn btn-success">Scan for Yeelights</a>
    </div>

    {{ form_end(form) }}


{% endblock %}

{% block javascripts %}
    <script src="/js/popper/popper.min.js"></script>
    <script src="/js/bootstrap/bootstrap.bundle.min.js"></script>
    <script src="/js/bootstrap/bootstrap-select.min.js"></script>
    <script src="/js/axios/axios.min.js"></script>
    <script>
        $(document).ready(function () {
            $('.js-add-widget').click(function (e) {
                var list = $($(this).attr('data-list-selector'));
                var counter = list.data('widget-counter') || list.children().length;

                var newWidget = list.attr('data-prototype');

                newWidget = newWidget.replace(/__deviceid__/g, counter);
                counter++;
                list.data('widget-counter', counter);

                $(list).append(newWidget);

                $('.selectpicker').selectpicker('refresh');
            });
        });

        document.querySelectorAll('.js-ajax').forEach(function (el) {
            el.addEventListener('click', function (e) {
                axios.get(e.currentTarget.dataset.url)
                    .catch(function (error) {
                        console.log(error);
                    })
                ;
            });
        });
    </script>
{% endblock %}

templates/dashboard/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ pageTitle }}{% endblock %}

{% block body %}
    <div class="row my-4">
        <div class="col-md-2">
            {% include 'dashboard/_menu.html.twig' with {'pageTitle': pageTitle} %}
        </div>
        <div class="col-md-10">
            <h1>{{ pageTitle }}</h1>
            {% block content %}
            {% endblock %}
        </div>
    </div>
{% endblock %}